# Generated by Django 2.0.2 on 2018-11-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trademark',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Marca'),
        ),
    ]
