# Generated by Django 2.0.2 on 2018-11-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181126_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products.Category', verbose_name='Categorías'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='trademark',
        ),
        migrations.AddField(
            model_name='product',
            name='trademark',
            field=models.ManyToManyField(related_name='products', to='products.Trademark', verbose_name='Marcas'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
