# Generated by Django 2.0.2 on 2018-11-27 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181126_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category', verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='trademark',
        ),
        migrations.AddField(
            model_name='product',
            name='trademark',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Trademark', verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
